[global]
pprof = ":6062"
# data center id
dc = "dc1"
# internet ip
addr = "192.168.1.97"

[pipeline.samplebuilder]
# max late for audio rtp packets
audiomaxlate = 100
# max late for video rtp packets
videomaxlate = 200

[pipeline.webmsaver]
enabled = true
togglable = true
defaulton = true
# webm output path
path = "./out/"

[rtp]
# listen port
port = 6668

# kcpkey = ""
# kcpsalt = ""
[log]
level = "info"

# level = "debug"
[etcd]
# ["ip:port", "ip:port"]
addrs = ["192.168.1.97:2389"]

[nats]
url = "nats://192.168.1.97:4222"
