[global]
pprof = ":6060"

# internet ip
addr = "192.168.1.97"

# data center id
dc = "dc1"

[log]
level = "info"
# level = "debug"

[etcd]
# ["ip:port", "ip:port"]
addrs = ["192.168.1.97:2389"]

[signal]
#listen ip port
host = "192.168.1.97"
port = "8443"
cert= "configs/certs/cert.pem"
key= "configs/certs/key.pem"
allow_disconnected = false

[nats]
url = "nats://192.168.1.97:4222"

