[global]
pprof = ":6061"

# data center id
dc = "dc1"

[log]
level = "info"

[etcd]
# ["ip:port", "ip:port"]
addrs = ["192.168.1.97:2389"]

[nats]
url = "nats://192.168.1.97:4222"

[redis]
addrs = ["192.168.1.97:6379"]
password = ""
db = 0
